# Inventario de Kubernetes
[all:vars]
ansible_user=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Nodo Master
[k8s_master]
k8s-master ansible_host=192.168.223.134

# Workers
[k8s_workers]
k8s-worker1 ansible_host=192.168.223.135
k8s-worker2 ansible_host=192.168.223.136

# Cluster
[k8s_cluster:children]
k8s_master
k8s_workers

# Variables
[k8s_cluster:vars]
k8s_version=1.28
pod_network_cidr=10.244.0.0/16
