apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunnywear-frontend
  namespace: bunnywear

spec:
  replicas: 1

  selector:
    matchLabels:
      app: bunnywear-frontend

  template:
    metadata:
      labels:
        app: bunnywear-frontend

    spec:
      containers:
      - name: frontend
        image: docker.io/c4rlos316/bunnywear-frontend:af0605bd2cf0175dc4f8f6324b51d49f294f82b6
        imagePullPolicy: Always

        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://django-backend:8000"

        ports:
        - containerPort: 3000
