apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - alertmanager.monitoring.svc.cluster.local:9093

    rule_files:
      - "/etc/prometheus/rules/*.yml"

    scrape_configs:

    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']

    - job_name: 'node-exporter'
      static_configs:
      - targets:
        - '192.168.223.134:9100'
        - '192.168.223.135:9100'
        - '192.168.223.136:9100'

    - job_name: 'kube-state-metrics'
      static_configs:
      - targets:
        - 'kube-state-metrics.monitoring.svc.cluster.local:8080'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"prometheus.yml":"global:\n  scrape_interval: 15s\n\nrule_files:\n  - \"/etc/prometheus/rules/*.yml\"\n\nscrape_configs:\n\n- job_name: 'prometheus'\n  static_configs:\n  - targets: ['localhost:9090']\n\n- job_name: 'node-exporter'\n  static_configs:\n  - targets:\n    - '192.168.223.134:9100'\n    - '192.168.223.135:9100'\n    - '192.168.223.136:9100'\n\n- job_name: 'kube-state-metrics'\n  static_configs:\n  - targets:\n    - 'kube-state-metrics.monitoring.svc.cluster.local:8080'\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2026-05-31T05:00:45Z","name":"prometheus-config","namespace":"monitoring","resourceVersion":"99118","uid":"a3488169-fd99-433a-8846-e6eea7ba154d"}}
  creationTimestamp: "2026-05-31T05:00:45Z"
  name: prometheus-config
  namespace: monitoring
  resourceVersion: "116763"
  uid: a3488169-fd99-433a-8846-e6eea7ba154d
