apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: bunnywear
type: Opaque
stringData:
  DB_NAME: "bunnywear_db"
  DB_USER: "bunnyuser"
  DB_PASSWORD: "bunnypass123"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DEBUG: "True"
  SECRET_KEY: "django-super-secret-key"
