apiVersion: v1
kind: Pod
metadata:
  name: pod-test-pvc
  namespace: bunnywear

spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]

      volumeMounts:
        - mountPath: /data
          name: storage

  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: pvc-test
