apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: bunnywear
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root123"
  MYSQL_DATABASE: "bunnywear_db"
  MYSQL_USER: "bunnyuser"
  MYSQL_PASSWORD: "bunnypass123"
