apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bunnywear-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/C4rlos316/bunnywear-devops.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: bunnywear

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
