apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bunnywear-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/C4rlos316/bunnywear-devops.git
    targetRevision: develop
    path: k8s

    directory:
      recurse: true
      include: '{00-namespace,02-mysql,03-backend-django,04-frontend-nextjs,05-ingress}/*'

  destination:
    server: https://kubernetes.default.svc
    namespace: bunnywear

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
