apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: bunnywear-frontend-run-
  namespace: tekton-pipelines

spec:
  taskRunTemplate:
    serviceAccountName: tekton-build-sa

  pipelineRef:
    name: bunnywear-frontend-pipeline

  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: tekton-workspace-pvc

    - name: dockerconfig
      secret:
        secretName: dockerhub-secret
